### PR TITLE
DraftailTextBlock to be searchable

### PR DESCRIPTION
**Pull request by dnsl48**
Currently DraftTextBlock returns its JSON stuff as the searchable content.
We want it to be the rendered document instead.

### CODE REVIEW

**Comment by loicteixeira** [comment]
It's a bit of a bummer that we have to render the html to then strip it but I don't see how else it can be done. The JSON structure doesn't seem very easy to traverse.

Would DraftailTextField need the same fix?

**Comment by dnsl48** [comment]
Yes, the text field implementation should be updated as well.
I'm also going to implement some tests. Will be doing things within this PR.

**Comment by dnsl48** [comment]
About having to render the content first - it's not a biggie, since wagtail database search backend doesn't support extra fields anyways, whereas Elasticsearch takes the stuff from fields only once - at the indexing stage (it's either on model update, or even in a celery/cron background job)

**Comment by loicteixeira** [comment]
Will add tests as part of in #27.

**Pull request merged**
